% function [meanBetas, subjects] = extractMeanBetas(Mask_file,SPM_dir,firstanalysispath)
%
% extractMeanBetas extracts the mean-beta-value in a predefined ROI/mask for
% a series of beta-files generated by SPM. This function has the purpose to
% derive activations for a correlation analysis or similar.
%
% IN:
% @SPM_dir: string of directory containing SPM.mat file of the 2nd-level contrast.
%
% @Mask_file: string of the name and location of the mask/ROI ('*.img')
% @Optional_path (optional): If need, add the path of the 1st level analysis,

% OUT:
% @meanBetas: vector containing the average of the ROI for each subject
%
% @subjects: list with subjects from which data was derived
%
% Tobias Hauser, 23.09.2013/27.02.2014/05.03.14/02.12.15
% K. Kadri, A. Marzuki 2025 : add check files 
function [meanBetas, subjects] = extractMeanBetas_fast(Mask_file,SPM_dir,Optional_path)

if nargin < 3
    Optional_path = '';
end
if nargin < 2
    SPM_dir = [spm_select(1,'dir','select 2ndL contrast') '\'];
end
if nargin < 1
    Mask_file = spm_select(1,'image','select mask');
end

curr_dir = pwd;

% load SPM
load([SPM_dir '/SPM.mat']);

% load mask
ROI = spm_vol(Mask_file);
[ROI_dat,XYZ] = spm_read_vols(ROI,0);
ROI_xyz = XYZ(:,find(ROI_dat > 0));    % mm space

% find beta-files
con_files = SPM.xY.P;
con_num = length(con_files);
SPM_files = dir(Optional_path); % Get all files and folders
SPM_files = SPM_files(~ismember({SPM_files.name}, {'.', '..'})); % Exclude '.' and '..'

if con_num ~= numel(SPM_files)
    error('Mismatch number of participants')
end


%If 1st level analysis done in a different path that the analysis script
for i = 1:con_num
    if ~exist(con_files{i}, 'dir') % Check if directory does not exist
        [~, name, ext] = fileparts(con_files{i}); % Extract the folder name
        subpath = [Optional_path, '/', SPM_files(i).name,'/'];
        dirPaths{i} = fullfile([subpath  name ext]); % Prepend '~/'
    end
end
% check if beta file exists 

% extract betas
betas = [];
subjects = [];
spm('CreateIntWin','on'); spm_progress_bar('Clear'); spm_progress_bar('Init',con_num,'subject','data extraction');
disp('extracting data...');
for b=1:con_num
    selected_outputs =dirPaths{b};
    % [selected_outputs] = regexp(pathstr,'\','split');
    try
        subjects(b) = str2double(SPM_files(b).name);
    catch
        warning('extracting subject number from path does not work.')
    end
    
    con_tmp = spm_vol(selected_outputs);
    xyz_tmp = con_tmp.mat\[ROI_xyz;ones(1,size(ROI_xyz,2))];
    betas(b,:) = spm_sample_vol(con_tmp,xyz_tmp(1,:),xyz_tmp(2,:),xyz_tmp(3,:),0);
    spm_progress_bar('Set', b);
end
spm_progress_bar('clear');

% average over voxels
meanBetas = nanmean(betas,2);


cd(curr_dir);

display('done');
end
